Db/seed data
2303-sustainable-snackwave/grace-shopper pull request #46
Opened 2023-08-20 00:31 UTC by TripolarHZ

finished creating dummy data for shipping and billing addresses, also made changes to billing address, shipping address, and user file.

2023-08-20 23:56 UTC, cmceachin5888 requested changes
please review comments. lets discuss if needed.

2023-08-20 23:56 UTC, cmceachin5888 commented on db/models/users.js
> +async function createUser({
I made some edits to users as well. i don't think adding billing/shipping info at creation is required. the users would add this info later to their profile or at checkout.

2023-08-20 23:56 UTC, cmceachin5888 commented on db/models/products.js
> +        return products;
i had to make some decent edits to products to get the tests to pass.

2023-08-21 01:02 UTC, Scarlette-O reviewed
As soon as you make the changes that Cameron requested i will add my approve.

2023-08-21 01:02 UTC, Scarlette-O commented on db/models/users.js
> +async function createUser({
Camron is right. Billing and shipping would be added to the profile i don't think its necessary when you create a user.

2023-08-21 23:25 UTC, cmceachin5888 approved these changes

2023-08-21 23:33 UTC, Scarlette-O approved these changes
looks good!

2023-08-21 23:34 UTC, merged