Db/checkout.js
2303-sustainable-snackwave/grace-shopper pull request #57
Opened 2023-08-22 00:23 UTC by Vimaser

2023-08-22 01:35 UTC, cmceachin5888 requested changes

2023-08-22 01:35 UTC, cmceachin5888 commented on db/models/checkout.js
> +const stripe = require('stripe')('SECRET_KEY'); // Replace secret_key
i would find a new place for this. maybe store in .env and advise the team what to update.

2023-08-22 01:52 UTC, Vimaser commented on db/models/checkout.js
> +const stripe = require('stripe')('SECRET_KEY'); // Replace secret_key
On it.

2023-08-23 00:13 UTC, cmceachin5888 approved these changes

2023-08-23 01:55 UTC, Scarlette-O approved these changes
Everything looks good.

2023-08-23 23:28 UTC, merged