finished reviews db
2303-sustainable-snackwave/grace-shopper pull request #59
Opened 2023-08-22 00:58 UTC by Scarlette-O

Finished db for reviews let me know if i should make any changes.

2023-08-22 01:18 UTC, Vimaser approved these changes
Looks good!

2023-08-22 01:44 UTC, cmceachin5888 requested changes

2023-08-22 01:44 UTC, cmceachin5888 commented on db/models/reviews.js
> +        INSERT INTO Reviews (ProductId, ReviewName, reviewerEmail, reviewDate)
dont use camel case here. 

also, review the table column names. you are not following the table we initially had.

CREATE TABLE product_reviews (
  id SERIAL PRIMARY KEY,
  product_id UUID NOT NULL,
  user_id INT NOT NULL,
  rating INT NOT NULL,
  review_text TEXT,
  review_date TIMESTAMP NOT NULL,
  FOREIGN KEY (product_id) REFERENCES products(id),
  FOREIGN KEY (user_id) REFERENCES users(id)
);

2023-08-22 01:44 UTC, cmceachin5888 commented on db/models/reviews.js
> +        FROM Reviews
should not be capitalized for "reviews"

2023-08-22 01:44 UTC, cmceachin5888 commented on db/models/reviews.js
> +        WHERE ProductID = $1
dont use camel case here

2023-08-23 01:52 UTC, Scarlette-O commented on db/models/reviews.js
> +        INSERT INTO Reviews (ProductId, ReviewName, reviewerEmail, reviewDate)
My bad I didnt even think to check if tables were already made. Will update and make changes asap.

2023-08-23 23:41 UTC, cmceachin5888 requested changes

2023-08-23 23:41 UTC, cmceachin5888 commented on db/models/reviews.js
> +async function createReview({ id, productId, userId, rating, reviewText, reviewDate }) {
you don't need "id"

createReview({ productId, userId, rating, reviewText, reviewDate })

2023-08-23 23:41 UTC, cmceachin5888 commented on db/models/reviews.js
> +        INSERT INTO reviews (id, ProductId, userId, rating, reviewText, reviewDate)
you dont need id

i think it should be (product_id, user_id, rating, review_text, review_date)

2023-08-23 23:41 UTC, cmceachin5888 commented on db/models/reviews.js
> +        VALUES ($1, $2, $3, $4, $5, $6)
no need for $6

2023-08-23 23:41 UTC, cmceachin5888 commented on db/models/reviews.js
> +            [id, productId, userId, rating, reviewText, reviewDate]
[productId, userId, rating, reviewText, reviewDate]);

2023-08-23 23:41 UTC, cmceachin5888 commented on db/models/reviews.js
> +        FROM reviews
async function getAllReviews() {
  try {
    const { rows } = await client.query(`
      SELECT pr.id, pr.rating, pr.review_text, pr.review_date,
             u.name as reviewer_name, u.email as reviewer_email,
             p.name as product_name
      FROM product_reviews pr
      INNER JOIN users u ON pr.user_id = u.id
      INNER JOIN products p ON pr.product_id = p.id
    `);

    return rows;
  } catch (error) {
    throw new Error('Error fetching reviews: ' + error.message);
  }
}

2023-08-23 23:41 UTC, cmceachin5888 commented on db/models/reviews.js
> +        FROM reviews
async function getReviewsByProduct(productId) {
  try {
    const { rows } = await client.query(`
      SELECT pr.id, pr.rating, pr.review_text, pr.review_date,
             u.name as reviewer_name, u.email as reviewer_email
      FROM product_reviews pr
      INNER JOIN users u ON pr.user_id = u.id
      WHERE pr.product_id = $1
    `, [productId]);

    return rows;
  } catch (error) {
    throw new Error('Error fetching reviews for product: ' + error.message);
  }
}

2023-08-23 23:41 UTC, cmceachin5888 commented on db/models/reviews.js
> +        INSERT INTO reviews (id, ProductId, userId, rating, reviewText, reviewDate)
INSERT INTO product_reviews

2023-08-24 00:25 UTC, cmceachin5888 approved these changes
looks good

2023-08-24 00:28 UTC, merged