Development
2303-sustainable-snackwave/grace-shopper pull request #64
Opened 2023-08-24 01:40 UTC by cmceachin5888

first pull development to main

2023-08-28 23:35 UTC, parisyee approved these changes
Great work so far! Just a few minor things but in general it looks really awesome. Can't wait for the frontend.

2023-08-28 23:35 UTC, parisyee commented on db/models/billingAddress.js
> +          const createdAddress = await createBillingAddress(
named parameters would be better here.

2023-08-29 01:45 UTC, cmceachin5888 commented on db/models/billingAddress.js
> +          const createdAddress = await createBillingAddress(
I will review

2023-08-29 01:47 UTC, cmceachin5888 commented on db/models/products.js
> +    if (requestingUserRole !== 'admin') {
i was debating and determined that we could have DB verification and then also have router verification. i didnt think more would hurt. 

we do have questions about the best way to do admin verification and updating.

2023-08-30 23:10 UTC, leafoflegend requested changes
There are quite a lot of security vulnerabilities in here.

My list priority ordered of how you should approach fixes:

1. Security commentary.
2. DRY up the app.
3. Fix entry point issues - make sure things that only need to be called once aren't called various times across the app.
4. Add a linter.
5. Time to get to frontend!

Loved that you have tests setup! That is a **GREAT** thing!

2023-08-30 23:10 UTC, leafoflegend commented on api/products.js
> +        message: "You must be logged in as an admin to perform this action",
Have you confirmed they are an `admin`? It looks like you've only confirmed they are a `user`, though I do infact see the `process.env.JWT_ADMIN`. I'll probably figure that out when I get lower to users.

2023-08-30 23:10 UTC, leafoflegend commented on api/reviews.js
> +router.use(bodyParser.json());
Ditto previous.

2023-08-30 23:10 UTC, leafoflegend commented on api/reviews.js
> +    const { productId, userId, rating, reviewText, reviewDate } = req.body;
I could post a review pretending to be any user if I have their `userId` handy.

2023-08-30 23:10 UTC, leafoflegend commented on api/users.js
> +      res.json(user);
Does this include their password in this information (I understand its encrypted, but still...).

2023-08-30 23:10 UTC, leafoflegend commented on api/users.js
> +        process.env.JWT_SECRET,
So the only way to end up an admin is if you were originally manually encrypted with that secret?

2023-08-30 23:10 UTC, leafoflegend commented on app.js
> +app.use(express.json());
These save you from having to use `bodyParser` at all.

Also, you could be some authentication middleware here that appends whether the user is authenticated or not.

2023-08-30 23:10 UTC, leafoflegend commented on db/.DS_Store
`.gitignore`

2023-08-30 23:10 UTC, leafoflegend commented on app.js
> +require("dotenv").config();
This should be the only place this is required.

2023-08-30 23:10 UTC, leafoflegend commented on server.js
> +const PORT = process.env["PORT"] || 3000
You haven't used `dotenv` here, so this won't work. You can move all the entry point logic to this file.

2023-08-30 23:10 UTC, leafoflegend commented on server.js
> +    chalk.blueBright("Get your Bike on!")
❤️ `chalk` ❤️

2023-08-30 23:10 UTC, leafoflegend commented on src/components/App.js
> +  );
This is the whole frontend right now?

2023-09-12 13:18 UTC, merged