Db/seed data
2303-sustainable-snackwave/grace-shopper pull request #65
Opened 2023-08-25 02:59 UTC by TripolarHZ

finished creation of all tables

2023-08-25 05:14 UTC, cmceachin5888 requested changes
let me know what you think

2023-08-25 05:14 UTC, cmceachin5888 commented on db/seedData.js
>          billing_address_id INTEGER REFERENCES billing_addresses(id)
change to "shipping"

2023-08-25 05:14 UTC, cmceachin5888 commented on db/models/users.js
> -}) {
i had to make several updates to Users.js as well. maybe you can revert yours so we dont conflict?

your change here for the addresses, whats the thought here? i have the tests passing as is, so i would need to edit them to accommodate.

2023-08-28 04:50 UTC, Scarlette-O approved these changes

2023-08-28 23:52 UTC, Vimaser approved these changes
Looks good. Checked in zoom.

2023-08-29 00:02 UTC, cmceachin5888 approved these changes

2023-08-29 00:02 UTC, merged